<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"节前信息管理",
			            "menuJump":"列表",
			            "tableName":"jieqianxinxi"
			        }
			    ],
			    "menu":"节前信息管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"表演项目管理",
                        "menuJump":"列表",
                        "tableName":"biaoyanxiangmu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"表演项目留言管理",
                        "menuJump":"列表",
                        "tableName":"biaoyanxiangmuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"表演项目收藏管理",
                        "menuJump":"列表",
                        "tableName":"biaoyanxiangmuCollection"
                    }
					 ,
					{
						"buttons":[
							"查看",
							"删除"
						],
						"menu":"表演项目报名管理",
						"menuJump":"列表",
						"tableName":"biaoyanxiangmuOrder"
					}
                ],
                "menu":"表演项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"比赛结果管理",
                        "menuJump":"列表",
                        "tableName":"bishaijieguo"
                    }
                ],
                "menu":"比赛结果管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"比赛项目管理",
                        "menuJump":"列表",
                        "tableName":"bishaixiangm"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"比赛项目留言管理",
                        "menuJump":"列表",
                        "tableName":"bishaixiangmLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"比赛项目收藏管理",
                        "menuJump":"列表",
                        "tableName":"bishaixiangmCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"比赛项目报名管理",
                        "menuJump":"列表",
                        "tableName":"bishaixiangmOrder"
                    }
                ],
                "menu":"比赛项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"表演类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBiaoyanxiangmu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"比赛类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBishaixiangm"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }

                ],
                "menu":"基础数据管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"节前信息管理",
			            "menuJump":"列表",
			            "tableName":"jieqianxinxi"
			        }
			    ],
			    "menu":"节前信息管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"表演项目管理",
	                    "menuJump":"列表",
	                    "tableName":"biaoyanxiangmu"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"表演项目留言管理",
	                    "menuJump":"列表",
	                    "tableName":"biaoyanxiangmuLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"表演项目收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"biaoyanxiangmuCollection"
	                }
					 ,
					{
						"buttons":[
							"查看"
						],
						"menu":"表演项目报名管理",
						"menuJump":"列表",
						"tableName":"biaoyanxiangmuOrder"
					}
	            ],
	            "menu":"表演项目管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"比赛结果管理",
	                    "menuJump":"列表",
	                    "tableName":"bishaijieguo"
	                }
	            ],
	            "menu":"比赛结果管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"比赛项目管理",
	                    "menuJump":"列表",
	                    "tableName":"bishaixiangm"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"比赛项目留言管理",
	                    "menuJump":"列表",
	                    "tableName":"bishaixiangmLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"比赛项目收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"bishaixiangmCollection"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"比赛项目报名管理",
	                    "menuJump":"列表",
	                    "tableName":"bishaixiangmOrder"
	                }
	            ],
	            "menu":"比赛项目管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
